name: Deploy

on: 
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          # password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ secrets.PROJECT_PATH }} && ls
          mkdir hai
      - run: echo "🍏 This job's status is ${{ job.status }}."