name: Deploy

on: 
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      # dimana distep pertama ini wajib ini artinya kita mau menggunakan branch mana.
      # - name: Checkout
      # uses: actions/checkout@master
      - uses: actions/checkout@v1
      #  menggunakan package untuk melakukan remote ssh ke server
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          # password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd ${{ secrets.PROJECT_PATH }} && ls
      - run: echo "🍏 This job's status is ${{ job.status }}."